### ISSUE TITLE
Make the SDK work with Node.js

### ISSUE THREAD

**Issue by DallanQ** [rootsdev/familysearch-javascript-sdk#8]
Add and end-to-end test as well

**Comment by justincy** [comment]
In theory this only requires finding http and promise libraries to pass in during initialization, right?

**Comment by justincy** [comment]
And then creating a `nodejs-wrappers.js` file and updating `intit.js` to properly detect when nodejs is being used.

Shouldn't be too bad...

**Comment by gengophers** [comment]
Exactly right. 

For the promise library you should be able to use https://github.com/kriskowal/q . Angular's promise library is modeled after this library.

For the http library you could consider using http://nodejs.org/api/http.html#http_http_request_options_callback

**Comment by DallanQ** [comment]
sorry - the previous comment was made by me.

**Comment by justincy** [comment]
Closed by #81. But not entirely useful until multiple instances are supported #42.
