### ISSUE TITLE
How do you logout of FamilySearch?

### ISSUE THREAD

**Issue by brenthale** [rootsdev/familysearch-javascript-sdk#80]
Hi,

I've got a simple app up and authenticating.  I am trying to wire up a way to logout.  I must be missing something very simple as I can't figure it out.   I can invalidate the sessionId by making an http GET call to the following:

            var logoutUrl = "https://sandbox.familysearch.org/identity/v2/logout?sessionId=";
            logoutUrl += $scope.sessionId;

This seems to succeed because if I call it twice in a row the second time it fails.

The problem seems to be that the FamilySearch object has no way of keeping track of the fact that a sessionId has been invalidated.  Probably because there is no FamilySearch.logout() function like (I at least) expected.

Once it is invalidated if I go to get the AccessToken() it simply returns the previous sessionId instead of re-authenticating.

Any Ideas?
Brent

**Comment by justincy** [comment]
The correct method with the SDK is to call [`invalidateAccessToken()`](http://rootsdev.org/familysearch-javascript-sdk/#/api/authentication.functions:invalidateAccessToken). Is that what you were looking for?

BTW, the `identify/v2` API has been deprecated.

**Comment by brenthale** [comment]
That's exactly what I needed.   Many thanks.
