### ISSUE TITLE
TypeError sometimes when signing in

### ISSUE THREAD

**Issue by justincy** [rootsdev/familysearch-javascript-sdk#95]
https://github.com/rootsdev/familysearch-javascript-sdk/blob/3665429b066384ae2e21917f1c691d2dae34e719/src/plumbing.js#L264

Should be `this.settings.accessToken`. The function `getAccessToken()` does not exist on the settings object.

**Comment by justincy** [comment]
The bug occurs when autoSignIn is enabled and a request is made to any endpoint other than oauth or discovery.

**Comment by dovy** [comment]
That's a fallback, how can we get access to that object?
